### ISSUE TITLE
Getting an error when src directory contains same name of file build should concat to

### ISSUE THREAD

**Issue by devinus** [aymericbeaumet/metalsmith-concat#12]
I have a file `app.scss` in my `src`.

I want to combine all compiled `*.css` from `*.scss` in `src` to the file `app.css` in `build`.

When I use `metalsmith-concat`, it complains that `app.css` already exists, even though it should not exist in `build`. It only exists as `app.scss` in `src`.

```
Error: The file "app.css" already exists
    at Ware.<anonymous> (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith-concat/lib/index.js:42:13)
    at Ware.<anonymous> (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith/node_modules/ware/lib/index.js:85:20)
    at /Users/devin/Projects/rebelmail-website/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:121:18
    at /Users/devin/Projects/rebelmail-website/node_modules/metalsmith-sass/node_modules/async/lib/async.js:52:16
    at done (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith-sass/node_modules/async/lib/async.js:248:21)
    at /Users/devin/Projects/rebelmail-website/node_modules/metalsmith-sass/node_modules/async/lib/async.js:44:16
    at Object.callback (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith-sass/lib/index.js:100:13)
    at options.success (/Users/devin/Projects/rebelmail-website/node_modules/metalsmith-sass/node_modules/node-sass/lib/index.js:293:32)
```

**Comment by aymericbeaumet** [comment]
Metalsmith-concat doesn't have the concept of `src` and `build`. In fact, it only knows about a `files` object which is passed as the parameter to the [plugin function](https://github.com/aymericbeaumet/metalsmith-concat/blob/66a68ff0df092c575924d8ef709284793bac7241/lib/index.js#L40).

As such if you have compiled `app.scss` to `app.css`, the key `app.css` already exists in file. Hence the error.

In your case it would work because I suppose `app.css` is going to be concatenated into the final output. But that's not always the case, and I don't want to handle a edge-case.
