### ISSUE TITLE
v6.0.3 metalsmith-concat@6.0.3 postinstall Fails

### ISSUE THREAD

**Issue by emmercm** [aymericbeaumet/metalsmith-concat#36]
I'm having this issue with a project of mine, but I get the error even with a new directory:

```bash
$ mkdir concat && cd concat && npm install --save metalsmith-concat

> metalsmith-concat@6.0.3 postinstall /Users/christianemmer/concat/node_modules/metalsmith-concat
> cd example && npm install

sh: line 0: cd: example: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/Users/christianemmer/concat/package.json'
npm WARN concat No description
npm WARN concat No repository field.
npm WARN concat No README data
npm WARN concat No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metalsmith-concat@6.0.3 postinstall: `cd example && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the metalsmith-concat@6.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christianemmer/.npm/_logs/2019-03-21T18_56_43_875Z-debug.log
```

Here's the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'metalsmith-concat' ]
2 info using npm@6.9.0
3 info using node@v8.9.0
4 verbose npm-session ae8496ea2325c999
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/metalsmith-concat 14ms (from cache)
8 silly pacote tag manifest for metalsmith-concat@latest fetched in 24ms
9 timing stage:loadCurrentTree Completed in 54ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule metalsmith-concat@6.0.3 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/async 18ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/minimatch 17ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/glob 19ms (from cache)
20 silly pacote version manifest for async@2.6.2 fetched in 23ms
21 silly resolveWithNewModule async@2.6.2 checking installable status
22 silly pacote version manifest for minimatch@3.0.4 fetched in 22ms
23 silly resolveWithNewModule minimatch@3.0.4 checking installable status
24 silly pacote version manifest for glob@7.1.3 fetched in 23ms
25 silly resolveWithNewModule glob@7.1.3 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/lodash 133ms (from cache)
27 silly pacote range manifest for lodash@^4.17.11 fetched in 135ms
28 silly resolveWithNewModule lodash@4.17.11 checking installable status
29 http fetch GET 200 https://registry.npmjs.org/fs.realpath 17ms (from cache)
30 http fetch GET 200 https://registry.npmjs.org/inherits 15ms (from cache)
31 http fetch GET 200 https://registry.npmjs.org/inflight 17ms (from cache)
32 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 16ms (from cache)
33 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 20ms
34 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
35 silly pacote range manifest for inherits@2 fetched in 19ms
36 silly resolveWithNewModule inherits@2.0.3 checking installable status
37 silly pacote range manifest for inflight@^1.0.4 fetched in 23ms
38 silly resolveWithNewModule inflight@1.0.6 checking installable status
39 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 37ms
40 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/once 47ms (from cache)
42 silly pacote range manifest for once@^1.3.0 fetched in 49ms
43 silly resolveWithNewModule once@1.4.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/wrappy 30ms (from cache)
45 silly pacote range manifest for wrappy@1 fetched in 31ms
46 silly resolveWithNewModule wrappy@1.0.2 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/brace-expansion 4ms (from cache)
48 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 5ms
49 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/balanced-match 7ms (from cache)
51 http fetch GET 200 https://registry.npmjs.org/concat-map 8ms (from cache)
52 silly pacote range manifest for balanced-match@^1.0.0 fetched in 9ms
53 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
54 silly pacote version manifest for concat-map@0.0.1 fetched in 9ms
55 silly resolveWithNewModule concat-map@0.0.1 checking installable status
56 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 272ms
57 timing stage:loadIdealTree Completed in 279ms
58 silly currentTree concat
59 silly idealTree concat
59 silly idealTree ├── async@2.6.2
59 silly idealTree ├── balanced-match@1.0.0
59 silly idealTree ├── brace-expansion@1.1.11
59 silly idealTree ├── concat-map@0.0.1
59 silly idealTree ├── fs.realpath@1.0.0
59 silly idealTree ├── glob@7.1.3
59 silly idealTree ├── inflight@1.0.6
59 silly idealTree ├── inherits@2.0.3
59 silly idealTree ├── lodash@4.17.11
59 silly idealTree ├── metalsmith-concat@6.0.3
59 silly idealTree ├── minimatch@3.0.4
59 silly idealTree ├── once@1.4.0
59 silly idealTree ├── path-is-absolute@1.0.1
59 silly idealTree └── wrappy@1.0.2
60 silly install generateActionsToTake
61 timing stage:generateActionsToTake Completed in 5ms
62 silly diffTrees action count 14
63 silly diffTrees add balanced-match@1.0.0
64 silly diffTrees add concat-map@0.0.1
65 silly diffTrees add brace-expansion@1.1.11
66 silly diffTrees add fs.realpath@1.0.0
67 silly diffTrees add inherits@2.0.3
68 silly diffTrees add lodash@4.17.11
69 silly diffTrees add minimatch@3.0.4
70 silly diffTrees add path-is-absolute@1.0.1
71 silly diffTrees add wrappy@1.0.2
72 silly diffTrees add once@1.4.0
73 silly diffTrees add inflight@1.0.6
74 silly diffTrees add async@2.6.2
75 silly diffTrees add glob@7.1.3
76 silly diffTrees add metalsmith-concat@6.0.3
77 silly decomposeActions action count 112
78 silly decomposeActions fetch balanced-match@1.0.0
79 silly decomposeActions extract balanced-match@1.0.0
80 silly decomposeActions preinstall balanced-match@1.0.0
81 silly decomposeActions build balanced-match@1.0.0
82 silly decomposeActions install balanced-match@1.0.0
83 silly decomposeActions postinstall balanced-match@1.0.0
84 silly decomposeActions finalize balanced-match@1.0.0
85 silly decomposeActions refresh-package-json balanced-match@1.0.0
86 silly decomposeActions fetch concat-map@0.0.1
87 silly decomposeActions extract concat-map@0.0.1
88 silly decomposeActions preinstall concat-map@0.0.1
89 silly decomposeActions build concat-map@0.0.1
90 silly decomposeActions install concat-map@0.0.1
91 silly decomposeActions postinstall concat-map@0.0.1
92 silly decomposeActions finalize concat-map@0.0.1
93 silly decomposeActions refresh-package-json concat-map@0.0.1
94 silly decomposeActions fetch brace-expansion@1.1.11
95 silly decomposeActions extract brace-expansion@1.1.11
96 silly decomposeActions preinstall brace-expansion@1.1.11
97 silly decomposeActions build brace-expansion@1.1.11
98 silly decomposeActions install brace-expansion@1.1.11
99 silly decomposeActions postinstall brace-expansion@1.1.11
100 silly decomposeActions finalize brace-expansion@1.1.11
101 silly decomposeActions refresh-package-json brace-expansion@1.1.11
102 silly decomposeActions fetch fs.realpath@1.0.0
103 silly decomposeActions extract fs.realpath@1.0.0
104 silly decomposeActions preinstall fs.realpath@1.0.0
105 silly decomposeActions build fs.realpath@1.0.0
106 silly decomposeActions install fs.realpath@1.0.0
107 silly decomposeActions postinstall fs.realpath@1.0.0
108 silly decomposeActions finalize fs.realpath@1.0.0
109 silly decomposeActions refresh-package-json fs.realpath@1.0.0
110 silly decomposeActions fetch inherits@2.0.3
111 silly decomposeActions extract inherits@2.0.3
112 silly decomposeActions preinstall inherits@2.0.3
113 silly decomposeActions build inherits@2.0.3
114 silly decomposeActions install inherits@2.0.3
115 silly decomposeActions postinstall inherits@2.0.3
116 silly decomposeActions finalize inherits@2.0.3
117 silly decomposeActions refresh-package-json inherits@2.0.3
118 silly decomposeActions fetch lodash@4.17.11
119 silly decomposeActions extract lodash@4.17.11
120 silly decomposeActions preinstall lodash@4.17.11
121 silly decomposeActions build lodash@4.17.11
122 silly decomposeActions install lodash@4.17.11
123 silly decomposeActions postinstall lodash@4.17.11
124 silly decomposeActions finalize lodash@4.17.11
125 silly decomposeActions refresh-package-json lodash@4.17.11
126 silly decomposeActions fetch minimatch@3.0.4
127 silly decomposeActions extract minimatch@3.0.4
128 silly decomposeActions preinstall minimatch@3.0.4
129 silly decomposeActions build minimatch@3.0.4
130 silly decomposeActions install minimatch@3.0.4
131 silly decomposeActions postinstall minimatch@3.0.4
132 silly decomposeActions finalize minimatch@3.0.4
133 silly decomposeActions refresh-package-json minimatch@3.0.4
134 silly decomposeActions fetch path-is-absolute@1.0.1
135 silly decomposeActions extract path-is-absolute@1.0.1
136 silly decomposeActions preinstall path-is-absolute@1.0.1
137 silly decomposeActions build path-is-absolute@1.0.1
138 silly decomposeActions install path-is-absolute@1.0.1
139 silly decomposeActions postinstall path-is-absolute@1.0.1
140 silly decomposeActions finalize path-is-absolute@1.0.1
141 silly decomposeActions refresh-package-json path-is-absolute@1.0.1
142 silly decomposeActions fetch wrappy@1.0.2
143 silly decomposeActions extract wrappy@1.0.2
144 silly decomposeActions preinstall wrappy@1.0.2
145 silly decomposeActions build wrappy@1.0.2
146 silly decomposeActions install wrappy@1.0.2
147 silly decomposeActions postinstall wrappy@1.0.2
148 silly decomposeActions finalize wrappy@1.0.2
149 silly decomposeActions refresh-package-json wrappy@1.0.2
150 silly decomposeActions fetch once@1.4.0
151 silly decomposeActions extract once@1.4.0
152 silly decomposeActions preinstall once@1.4.0
153 silly decomposeActions build once@1.4.0
154 silly decomposeActions install once@1.4.0
155 silly decomposeActions postinstall once@1.4.0
156 silly decomposeActions finalize once@1.4.0
157 silly decomposeActions refresh-package-json once@1.4.0
158 silly decomposeActions fetch inflight@1.0.6
159 silly decomposeActions extract inflight@1.0.6
160 silly decomposeActions preinstall inflight@1.0.6
161 silly decomposeActions build inflight@1.0.6
162 silly decomposeActions install inflight@1.0.6
163 silly decomposeActions postinstall inflight@1.0.6
164 silly decomposeActions finalize inflight@1.0.6
165 silly decomposeActions refresh-package-json inflight@1.0.6
166 silly decomposeActions fetch async@2.6.2
167 silly decomposeActions extract async@2.6.2
168 silly decomposeActions preinstall async@2.6.2
169 silly decomposeActions build async@2.6.2
170 silly decomposeActions install async@2.6.2
171 silly decomposeActions postinstall async@2.6.2
172 silly decomposeActions finalize async@2.6.2
173 silly decomposeActions refresh-package-json async@2.6.2
174 silly decomposeActions fetch glob@7.1.3
175 silly decomposeActions extract glob@7.1.3
176 silly decomposeActions preinstall glob@7.1.3
177 silly decomposeActions build glob@7.1.3
178 silly decomposeActions install glob@7.1.3
179 silly decomposeActions postinstall glob@7.1.3
180 silly decomposeActions finalize glob@7.1.3
181 silly decomposeActions refresh-package-json glob@7.1.3
182 silly decomposeActions fetch metalsmith-concat@6.0.3
183 silly decomposeActions extract metalsmith-concat@6.0.3
184 silly decomposeActions preinstall metalsmith-concat@6.0.3
185 silly decomposeActions build metalsmith-concat@6.0.3
186 silly decomposeActions install metalsmith-concat@6.0.3
187 silly decomposeActions postinstall metalsmith-concat@6.0.3
188 silly decomposeActions finalize metalsmith-concat@6.0.3
189 silly decomposeActions refresh-package-json metalsmith-concat@6.0.3
190 silly install executeActions
191 silly doSerial global-install 112
192 verbose correctMkdir /Users/christianemmer/.npm/_locks correctMkdir not in flight; initializing
193 verbose lock using /Users/christianemmer/.npm/_locks/staging-49858fa223067bb7.lock for /Users/christianemmer/concat/node_modules/.staging
194 silly doParallel extract 14
195 silly extract balanced-match@1.0.0
196 silly extract concat-map@0.0.1
197 silly extract brace-expansion@1.1.11
198 silly extract fs.realpath@1.0.0
199 silly extract inherits@2.0.3
200 silly extract lodash@4.17.11
201 silly extract minimatch@3.0.4
202 silly extract path-is-absolute@1.0.1
203 silly extract wrappy@1.0.2
204 silly extract once@1.4.0
205 silly extract inflight@1.0.6
206 silly extract async@2.6.2
207 silly extract glob@7.1.3
208 silly extract metalsmith-concat@6.0.3
209 silly tarball trying balanced-match@^1.0.0 by hash: sha1-ibTRmasr7kneFk6gK4nORi1xt2c=
210 silly tarball trying concat-map@0.0.1 by hash: sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=
211 silly tarball trying brace-expansion@^1.1.7 by hash: sha512-iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==
212 silly tarball trying fs.realpath@^1.0.0 by hash: sha1-FQStJSMVjKpA20onh8sBQRmU6k8=
213 silly tarball trying inherits@2 by hash: sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=
214 silly tarball trying lodash@^4.17.11 by hash: sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==
215 silly tarball trying minimatch@3.0.4 by hash: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==
216 silly tarball trying path-is-absolute@^1.0.0 by hash: sha1-F0uSaHNVNP+8es5r9TpanhtcX18=
217 silly tarball trying wrappy@1 by hash: sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=
218 silly tarball trying once@^1.3.0 by hash: sha1-WDsap3WWHUsROsF9nFC6753Xa9E=
219 silly tarball trying inflight@^1.0.4 by hash: sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=
220 silly tarball trying async@2.6.2 by hash: sha512-H1qVYh1MYhEEFLsP97cVKqCGo7KfCyTt6uEWqsTBr9SO84oK9Uwbyd/yCW+6rKJLHksBNUVWZDAjfS+Ccx0Bbg==
221 silly tarball trying glob@7.1.3 by hash: sha512-vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==
222 silly tarball trying metalsmith-concat@latest by hash: sha512-MDIbOwgd0/cRYH7nVT/2pSnLfytIIrhETC/baa5dvjggYWVM419P8JZYE4MLz4eqLWIgfVDO47Lg38QdRVDFig==
223 silly extract balanced-match@^1.0.0 extracted to /Users/christianemmer/concat/node_modules/.staging/balanced-match-be3a5105 (84ms)
224 silly extract brace-expansion@^1.1.7 extracted to /Users/christianemmer/concat/node_modules/.staging/brace-expansion-13b0adb0 (84ms)
225 silly extract path-is-absolute@^1.0.0 extracted to /Users/christianemmer/concat/node_modules/.staging/path-is-absolute-6687f3f8 (83ms)
226 silly extract wrappy@1 extracted to /Users/christianemmer/concat/node_modules/.staging/wrappy-78567798 (82ms)
227 silly extract inflight@^1.0.4 extracted to /Users/christianemmer/concat/node_modules/.staging/inflight-6074e631 (82ms)
228 silly extract once@^1.3.0 extracted to /Users/christianemmer/concat/node_modules/.staging/once-3a83d859 (82ms)
229 silly extract inherits@2 extracted to /Users/christianemmer/concat/node_modules/.staging/inherits-710e3a9d (86ms)
230 silly extract fs.realpath@^1.0.0 extracted to /Users/christianemmer/concat/node_modules/.staging/fs.realpath-f54e9de5 (86ms)
231 silly extract minimatch@3.0.4 extracted to /Users/christianemmer/concat/node_modules/.staging/minimatch-75157db3 (85ms)
232 silly extract metalsmith-concat@latest extracted to /Users/christianemmer/concat/node_modules/.staging/metalsmith-concat-6e751860 (84ms)
233 silly extract concat-map@0.0.1 extracted to /Users/christianemmer/concat/node_modules/.staging/concat-map-8a603632 (89ms)
234 silly extract glob@7.1.3 extracted to /Users/christianemmer/concat/node_modules/.staging/glob-d4851790 (85ms)
235 silly extract async@2.6.2 extracted to /Users/christianemmer/concat/node_modules/.staging/async-a9c5d498 (124ms)
236 silly extract lodash@^4.17.11 extracted to /Users/christianemmer/concat/node_modules/.staging/lodash-514f5f9d (280ms)
237 timing action:extract Completed in 284ms
238 silly doReverseSerial unbuild 112
239 silly doSerial remove 112
240 silly doSerial move 112
241 silly doSerial finalize 112
242 silly finalize /Users/christianemmer/concat/node_modules/balanced-match
243 silly finalize /Users/christianemmer/concat/node_modules/concat-map
244 silly finalize /Users/christianemmer/concat/node_modules/brace-expansion
245 silly finalize /Users/christianemmer/concat/node_modules/fs.realpath
246 silly finalize /Users/christianemmer/concat/node_modules/inherits
247 silly finalize /Users/christianemmer/concat/node_modules/lodash
248 silly finalize /Users/christianemmer/concat/node_modules/minimatch
249 silly finalize /Users/christianemmer/concat/node_modules/path-is-absolute
250 silly finalize /Users/christianemmer/concat/node_modules/wrappy
251 silly finalize /Users/christianemmer/concat/node_modules/once
252 silly finalize /Users/christianemmer/concat/node_modules/inflight
253 silly finalize /Users/christianemmer/concat/node_modules/async
254 silly finalize /Users/christianemmer/concat/node_modules/glob
255 silly finalize /Users/christianemmer/concat/node_modules/metalsmith-concat
256 timing action:finalize Completed in 16ms
257 silly doParallel refresh-package-json 14
258 silly refresh-package-json /Users/christianemmer/concat/node_modules/balanced-match
259 silly refresh-package-json /Users/christianemmer/concat/node_modules/concat-map
260 silly refresh-package-json /Users/christianemmer/concat/node_modules/brace-expansion
261 silly refresh-package-json /Users/christianemmer/concat/node_modules/fs.realpath
262 silly refresh-package-json /Users/christianemmer/concat/node_modules/inherits
263 silly refresh-package-json /Users/christianemmer/concat/node_modules/lodash
264 silly refresh-package-json /Users/christianemmer/concat/node_modules/minimatch
265 silly refresh-package-json /Users/christianemmer/concat/node_modules/path-is-absolute
266 silly refresh-package-json /Users/christianemmer/concat/node_modules/wrappy
267 silly refresh-package-json /Users/christianemmer/concat/node_modules/once
268 silly refresh-package-json /Users/christianemmer/concat/node_modules/inflight
269 silly refresh-package-json /Users/christianemmer/concat/node_modules/async
270 silly refresh-package-json /Users/christianemmer/concat/node_modules/glob
271 silly refresh-package-json /Users/christianemmer/concat/node_modules/metalsmith-concat
272 timing action:refresh-package-json Completed in 33ms
273 silly doParallel preinstall 14
274 silly preinstall balanced-match@1.0.0
275 info lifecycle balanced-match@1.0.0~preinstall: balanced-match@1.0.0
276 silly preinstall concat-map@0.0.1
277 info lifecycle concat-map@0.0.1~preinstall: concat-map@0.0.1
278 silly preinstall brace-expansion@1.1.11
279 info lifecycle brace-expansion@1.1.11~preinstall: brace-expansion@1.1.11
280 silly preinstall fs.realpath@1.0.0
281 info lifecycle fs.realpath@1.0.0~preinstall: fs.realpath@1.0.0
282 silly preinstall inherits@2.0.3
283 info lifecycle inherits@2.0.3~preinstall: inherits@2.0.3
284 silly preinstall lodash@4.17.11
285 info lifecycle lodash@4.17.11~preinstall: lodash@4.17.11
286 silly preinstall minimatch@3.0.4
287 info lifecycle minimatch@3.0.4~preinstall: minimatch@3.0.4
288 silly preinstall path-is-absolute@1.0.1
289 info lifecycle path-is-absolute@1.0.1~preinstall: path-is-absolute@1.0.1
290 silly preinstall wrappy@1.0.2
291 info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
292 silly preinstall once@1.4.0
293 info lifecycle once@1.4.0~preinstall: once@1.4.0
294 silly preinstall inflight@1.0.6
295 info lifecycle inflight@1.0.6~preinstall: inflight@1.0.6
296 silly preinstall async@2.6.2
297 info lifecycle async@2.6.2~preinstall: async@2.6.2
298 silly preinstall glob@7.1.3
299 info lifecycle glob@7.1.3~preinstall: glob@7.1.3
300 silly preinstall metalsmith-concat@6.0.3
301 info lifecycle metalsmith-concat@6.0.3~preinstall: metalsmith-concat@6.0.3
302 timing action:preinstall Completed in 2ms
303 silly doSerial build 112
304 silly build balanced-match@1.0.0
305 info linkStuff balanced-match@1.0.0
306 silly linkStuff balanced-match@1.0.0 has /Users/christianemmer/concat/node_modules as its parent node_modules
307 silly build concat-map@0.0.1
308 info linkStuff concat-map@0.0.1
309 silly linkStuff concat-map@0.0.1 has /Users/christianemmer/concat/node_modules as its parent node_modules
310 silly build brace-expansion@1.1.11
311 info linkStuff brace-expansion@1.1.11
312 silly linkStuff brace-expansion@1.1.11 has /Users/christianemmer/concat/node_modules as its parent node_modules
313 silly build fs.realpath@1.0.0
314 info linkStuff fs.realpath@1.0.0
315 silly linkStuff fs.realpath@1.0.0 has /Users/christianemmer/concat/node_modules as its parent node_modules
316 silly build inherits@2.0.3
317 info linkStuff inherits@2.0.3
318 silly linkStuff inherits@2.0.3 has /Users/christianemmer/concat/node_modules as its parent node_modules
319 silly build lodash@4.17.11
320 info linkStuff lodash@4.17.11
321 silly linkStuff lodash@4.17.11 has /Users/christianemmer/concat/node_modules as its parent node_modules
322 silly build minimatch@3.0.4
323 info linkStuff minimatch@3.0.4
324 silly linkStuff minimatch@3.0.4 has /Users/christianemmer/concat/node_modules as its parent node_modules
325 silly build path-is-absolute@1.0.1
326 info linkStuff path-is-absolute@1.0.1
327 silly linkStuff path-is-absolute@1.0.1 has /Users/christianemmer/concat/node_modules as its parent node_modules
328 silly build wrappy@1.0.2
329 info linkStuff wrappy@1.0.2
330 silly linkStuff wrappy@1.0.2 has /Users/christianemmer/concat/node_modules as its parent node_modules
331 silly build once@1.4.0
332 info linkStuff once@1.4.0
333 silly linkStuff once@1.4.0 has /Users/christianemmer/concat/node_modules as its parent node_modules
334 silly build inflight@1.0.6
335 info linkStuff inflight@1.0.6
336 silly linkStuff inflight@1.0.6 has /Users/christianemmer/concat/node_modules as its parent node_modules
337 silly build async@2.6.2
338 info linkStuff async@2.6.2
339 silly linkStuff async@2.6.2 has /Users/christianemmer/concat/node_modules as its parent node_modules
340 silly build glob@7.1.3
341 info linkStuff glob@7.1.3
342 silly linkStuff glob@7.1.3 has /Users/christianemmer/concat/node_modules as its parent node_modules
343 silly build metalsmith-concat@6.0.3
344 info linkStuff metalsmith-concat@6.0.3
345 silly linkStuff metalsmith-concat@6.0.3 has /Users/christianemmer/concat/node_modules as its parent node_modules
346 timing action:build Completed in 2ms
347 silly doSerial global-link 112
348 silly doParallel update-linked 0
349 silly doSerial install 112
350 silly install balanced-match@1.0.0
351 info lifecycle balanced-match@1.0.0~install: balanced-match@1.0.0
352 silly install concat-map@0.0.1
353 info lifecycle concat-map@0.0.1~install: concat-map@0.0.1
354 silly install brace-expansion@1.1.11
355 info lifecycle brace-expansion@1.1.11~install: brace-expansion@1.1.11
356 silly install fs.realpath@1.0.0
357 info lifecycle fs.realpath@1.0.0~install: fs.realpath@1.0.0
358 silly install inherits@2.0.3
359 info lifecycle inherits@2.0.3~install: inherits@2.0.3
360 silly install lodash@4.17.11
361 info lifecycle lodash@4.17.11~install: lodash@4.17.11
362 silly install minimatch@3.0.4
363 info lifecycle minimatch@3.0.4~install: minimatch@3.0.4
364 silly install path-is-absolute@1.0.1
365 info lifecycle path-is-absolute@1.0.1~install: path-is-absolute@1.0.1
366 silly install wrappy@1.0.2
367 info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
368 silly install once@1.4.0
369 info lifecycle once@1.4.0~install: once@1.4.0
370 silly install inflight@1.0.6
371 info lifecycle inflight@1.0.6~install: inflight@1.0.6
372 silly install async@2.6.2
373 info lifecycle async@2.6.2~install: async@2.6.2
374 silly install glob@7.1.3
375 info lifecycle glob@7.1.3~install: glob@7.1.3
376 silly install metalsmith-concat@6.0.3
377 info lifecycle metalsmith-concat@6.0.3~install: metalsmith-concat@6.0.3
378 timing action:install Completed in 2ms
379 silly doSerial postinstall 112
380 silly postinstall balanced-match@1.0.0
381 info lifecycle balanced-match@1.0.0~postinstall: balanced-match@1.0.0
382 silly postinstall concat-map@0.0.1
383 info lifecycle concat-map@0.0.1~postinstall: concat-map@0.0.1
384 silly postinstall brace-expansion@1.1.11
385 info lifecycle brace-expansion@1.1.11~postinstall: brace-expansion@1.1.11
386 silly postinstall fs.realpath@1.0.0
387 info lifecycle fs.realpath@1.0.0~postinstall: fs.realpath@1.0.0
388 silly postinstall inherits@2.0.3
389 info lifecycle inherits@2.0.3~postinstall: inherits@2.0.3
390 silly postinstall lodash@4.17.11
391 info lifecycle lodash@4.17.11~postinstall: lodash@4.17.11
392 silly postinstall minimatch@3.0.4
393 info lifecycle minimatch@3.0.4~postinstall: minimatch@3.0.4
394 silly postinstall path-is-absolute@1.0.1
395 info lifecycle path-is-absolute@1.0.1~postinstall: path-is-absolute@1.0.1
396 silly postinstall wrappy@1.0.2
397 info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
398 silly postinstall once@1.4.0
399 info lifecycle once@1.4.0~postinstall: once@1.4.0
400 silly postinstall inflight@1.0.6
401 info lifecycle inflight@1.0.6~postinstall: inflight@1.0.6
402 timing audit submit Completed in 353ms
403 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 353ms
404 silly postinstall async@2.6.2
405 info lifecycle async@2.6.2~postinstall: async@2.6.2
406 timing audit body Completed in 0ms
407 silly postinstall glob@7.1.3
408 info lifecycle glob@7.1.3~postinstall: glob@7.1.3
409 silly postinstall metalsmith-concat@6.0.3
410 info lifecycle metalsmith-concat@6.0.3~postinstall: metalsmith-concat@6.0.3
411 verbose lifecycle metalsmith-concat@6.0.3~postinstall: unsafe-perm in lifecycle true
412 verbose lifecycle metalsmith-concat@6.0.3~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/christianemmer/concat/node_modules/metalsmith-concat/node_modules/.bin:/Users/christianemmer/concat/node_modules/.bin:/Users/christianemmer/.sdkman/candidates/kotlin/current/bin:/Users/christianemmer/.sdkman/candidates/java/current/bin:/Users/christianemmer/.sdkman/candidates/gradle/current/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/christianemmer/go/bin:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/mysql@5.7/bin:/Users/christianemmer/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin
413 verbose lifecycle metalsmith-concat@6.0.3~postinstall: CWD: /Users/christianemmer/concat/node_modules/metalsmith-concat
414 silly lifecycle metalsmith-concat@6.0.3~postinstall: Args: [ '-c', 'cd example && npm install' ]
415 silly lifecycle metalsmith-concat@6.0.3~postinstall: Returned: code: 1  signal: null
416 info lifecycle metalsmith-concat@6.0.3~postinstall: Failed to exec postinstall script
417 timing action:postinstall Completed in 17ms
418 verbose unlock done using /Users/christianemmer/.npm/_locks/staging-49858fa223067bb7.lock for /Users/christianemmer/concat/node_modules/.staging
419 timing stage:rollbackFailedOptional Completed in 131ms
420 timing stage:runTopLevelLifecycles Completed in 849ms
421 silly saveTree concat
421 silly saveTree └─┬ metalsmith-concat@6.0.3
421 silly saveTree   ├─┬ async@2.6.2
421 silly saveTree   │ └── lodash@4.17.11
421 silly saveTree   ├─┬ glob@7.1.3
421 silly saveTree   │ ├── fs.realpath@1.0.0
421 silly saveTree   │ ├─┬ inflight@1.0.6
421 silly saveTree   │ │ ├─┬ once@1.4.0
421 silly saveTree   │ │ │ └── wrappy@1.0.2
421 silly saveTree   │ │ └── wrappy@1.0.2
421 silly saveTree   │ ├── inherits@2.0.3
421 silly saveTree   │ ├─┬ minimatch@3.0.4
421 silly saveTree   │ │ └─┬ brace-expansion@1.1.11
421 silly saveTree   │ │   ├── balanced-match@1.0.0
421 silly saveTree   │ │   └── concat-map@0.0.1
421 silly saveTree   │ ├── once@1.4.0
421 silly saveTree   │ └── path-is-absolute@1.0.1
421 silly saveTree   └── minimatch@3.0.4
422 warn enoent ENOENT: no such file or directory, open '/Users/christianemmer/concat/package.json'
423 verbose enoent This is related to npm not being able to find a file.
424 warn concat No description
425 warn concat No repository field.
426 warn concat No README data
427 warn concat No license field.
428 verbose stack Error: metalsmith-concat@6.0.3 postinstall: `cd example && npm install`
428 verbose stack Exit status 1
428 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
428 verbose stack     at emitTwo (events.js:126:13)
428 verbose stack     at EventEmitter.emit (events.js:214:7)
428 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
428 verbose stack     at emitTwo (events.js:126:13)
428 verbose stack     at ChildProcess.emit (events.js:214:7)
428 verbose stack     at maybeClose (internal/child_process.js:925:16)
428 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
429 verbose pkgid metalsmith-concat@6.0.3
430 verbose cwd /Users/christianemmer/concat
431 verbose Darwin 18.2.0
432 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "metalsmith-concat"
433 verbose node v8.9.0
434 verbose npm  v6.9.0
435 error code ELIFECYCLE
436 error errno 1
437 error metalsmith-concat@6.0.3 postinstall: `cd example && npm install`
437 error Exit status 1
438 error Failed at the metalsmith-concat@6.0.3 postinstall script.
438 error This is probably not a problem with npm. There is likely additional logging output above.
439 verbose exit [ 1, true ]
```

I'm on OSX 10.14.3 with Node v8.9.0.

**Comment by colophonemes** [comment]
+1

Downgrading to `metalsmith-concat@5` has worked fine as a workaround, though it has a potentially insecure `minimatch` dependency:

```
warning metalsmith-concat > minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by aymericbeaumet** [comment]
Hello there, I apologize for the delay. I just published a new version which resolves this issue among a few other things 👍
